name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - oh-my-posh
          - shovel
        baseImage:
          - mcr.microsoft.com/devcontainers/base:ubuntu
          - mcr.microsoft.com/devcontainers/base:alpine
    steps:
      - uses: actions/checkout@v2

      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'
        run: devcontainer features test -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Testing global scenarios
        run: devcontainer features test --global-scenarios-only .
